### ISSUE TITLE
Error when loading these data frames (local variable 'arr' referenced before assignment)

### ISSUE THREAD

**Issue by elisabeth-chen** [CancerRxGene/gdsctools#150]
Loading these data frames and running anova_all() or anova_one_drug results in error for me:

UnboundLocalError: local variable 'arr' referenced before assignment

[test_files.zip](https://github.com/CancerRxGene/gdsctools/files/347817/test_files.zip)

**Comment by cokelaer** [comment]
Hi Liz, 
The error comes from the fact that the data configuration does not fit in the available regression.
That is your data has a MEDIA factor, TISSUE ( obviously), and FEATURE but not MSI factor is included despite the fact that you provide a column with MSI because all values are set to 1.

There is a condition in GDSCTools that requires at least some balance in the MSI columns: at least 2 ones or 2 zeros are required. So in your case MSI is not included. 

If you look at the documentation here: 

http://gdsctools.readthedocs.io/en/master/anova_parttwo.html#regression-analysis

you will see that the FEATURE is always required but MSI is also required if you want to include the MEDIA factor. 

We could implement a new regression case in a next release.

**Comment by elisabeth-chen** [comment]
Hi Thomas, 

Thanks for looking into this for me!
Unfortunately, the error still persists when I change the MSI status of some random cell lines to 0 and when I set settings.include_MSI_factor and settings.include_media_factor = False. 

Do you have any idea what else I could try?

**Comment by cokelaer** [comment]
I have changed 4 values from 1 to 0 in the MSI column and now it is running.

If I do not change the data and set 

    an.settings.include_media_factor = False

it runs as well.

If I set include_media_factor and msi_factor to False keeping original data, it runs as well.

Does it fail at the beginning and does the progress bar starts and fails after a while ?

**Comment by elisabeth-chen** [comment]
Hi Thomas!

Thanks for checking it for me! 
I changed some random cell lines and tried several cases now. For me, some of them work and some don't. What I have found so far is:

1. If I read in data using the Readers and then pass that to the ANOVA function, the error occurs. 
2. If I run ANOVA( "ic1_input.csv", "gf_input.csv", "dd_input.csv" ) and then an.anova_all(), it works (currently running)
3. If I do the same as in step 2, but then try to change settings.include_MSI_factor and settings.include_media_factor = False, it doesn't work.

Every time it gives me the same error as the original error.

Don't know what the problem here might be...

**Comment by cokelaer** [comment]
There are four possible regressions::

- Y ~ C(tissue) + C(media) + C(MSI) + Feature
- Y ~ C(tissue) + C(MSI) + Feature
- Y ~ C(MSI) + Feature
- Y ~ Feature

So if MSI is not included, only the fourth case is possible. I will add code to raise an explicit error
Otherwise, it is indeed difficult to understand what is going on.

http://gdsctools.readthedocs.io/en/master/anova_parttwo.html

**Comment by cokelaer** [comment]
The new version v0.15.0 still works as in the previous comment with only 4 possible regression types.
Note, however, that a new settings:

   settings.regression_formula

is now available and can be used to set any formula so you can now do::

Y ~ C(tissue) + Feature

for instance. This is, however, a bit slower than the 4 standard cases.

**Comment by cokelaer** [comment]
This should now be working in v0.16 (in the github only for now)
