### ISSUE TITLE
Error when creating html pages

### ISSUE THREAD

**Issue by elisabeth-chen** [CancerRxGene/gdsctools#151]
Hi Thomas, 

After running the analysis as in the previous issue (#150), I tried to create the html pages. It runs well for drugs and features. It also creates association pages for the first two associations, but for the third one, it gives me a long error. 
I'm attaching the error to this thread. 
[error-create_html_pages.txt](https://github.com/CancerRxGene/gdsctools/files/390597/error-create_html_pages.txt)

(Btw, I am using a slightly different data set from the previous test-files that I attached, so if you need those, please let me know and I will send them to you via e-mail!)

Thanks,

Liz

EDIT: also, looking at the report, the drug name and drug target fields are not populated, even when specifying the drug decoder at the ANOVA and ANOVAReport stage (and the drug decode table is correctly shown in the "INPUT" folder). 

EDIT2: On the issue of drug name and drug target: fields were not populated correctly because DRUG ID column in "dd_input.csv" is not a string. Would perhaps be nice to have a warning built in when this is the case. 
Also, not sure if this is intended, but when the drug ID is too long (one of mine had about 20 characters), all drugIDs are converted into "string" character. I resolved this by deleting offending row, but may be good to have a note on that.

**Comment by cokelaer** [comment]
Answer to EDIT2:

Indeed, an identifiers must be less than 2**64 -1 to be converted to an integer on a 64bit machine. In Python, I think 32 or 64 bits machine can handle 64bits integer. Yet, it is a limitation indeed. 2 to the power 64 correspond to about 20 digits as you did notice.

So, I've added a piece of code that will (1) put a warning in such cases and (2) change the identifier to have only 20 digits. If several identifiers have the same value, this will lead to an error

Answer to EDIT1: fix to EDIT2 and other fixes should fix also the issue with the report

This will be fixed in v0.16
